FIX: The cjs template does not use MVC architecture pattern yet
code-collabo/node-mongo-api-boilerplate-templates pull request #3
Opened 2023-04-12 14:48 UTC by samuko-things

**This pull request makes the following changes:**
* Fixes code-collabo/node-mongo-api-boilerplate-templates #8 

**General checklist**
- [x] all GET, POST, PATCH, PUT and DELETE requests have been restructed to use MVC: Models, routes, services and controllers are separated and in different files.
- [x] Retains the use of .then() syntax and makes use of regular functions.
- [x] The function names and variable names are same as the ones found in the routes, controllers and services files of the ts template.
- [x] No new code or functionality was added, I only restructured existing code to use MVC pattern.
- [x] I certify that I ran my checklist

Ping @code-collabo/node-mongo-api-boilerplate-templates

2023-04-12 14:53 UTC, samuko-things commented
I have just restructured the cjs api template. do check it out

2023-04-13 06:39 UTC, Ifycode requested changes

2023-04-13 06:39 UTC, Ifycode commented on cjs/src/api/services/demo.service.js
> +// });
@samuko-things Nice work. I haven't tested that it works yet. But you should also restructure patch and put to mvc too.

2023-04-13 06:43 UTC, Ifycode commented on cjs/src/api/services/demo.service.js
> +// });
Also note: 
- You shouldn't remove the general checklist.
- The space before the #8 does not make it link your PR to the issue properly. Please link the issue

2023-04-14 14:58 UTC, samuko-things commented
i have just restructured the patch and put, do check it out.

2023-04-15 20:55 UTC, Ifycode requested changes

2023-04-15 20:55 UTC, Ifycode commented on cjs/src/api/controllers/demo.controller.js
> +const partialUpdateDemoItemController = (req, res, next) => {
- Same thing for the cjs template. Change the function names accordingly and rearrange as I have said in Review comments 1, 2 & 3 in #4

2023-04-17 11:14 UTC, samuko-things commented
i have renamed the patch and put function as requested. do check it out

2023-04-17 21:24 UTC, samuko-things commented
i have updated the cjs template api and also updated the app.js file to track the API routes

2023-04-17 22:19 UTC, samuko-things commented
i have also tested it with atlas, and its working well. it also has a few warnings and error (which does not affect its functionality).

2023-04-18 21:53 UTC, Ifycode commented
Thank you @samuko-things
I will check it out.
But I can't do that until you have corrected the prettier mess in the ts template PR. Once you have done that, I will review all 3 PRs submitted so far.

2023-04-18 22:20 UTC, Ifycode approved these changes

2023-04-18 22:22 UTC, merged