FIX: PATCH and Put requests omitted in ts template
code-collabo/node-mongo-api-boilerplate-templates pull request #5
Opened 2023-04-14 15:28 UTC by samuko-things

**This pull request makes the following changes:**
* Fixes code-collabo/node-mongo#6

**General checklist**
- [x] PATCH code/request has been added and restructured to use MVC: Models, routes, services and controllers are separated and in different files.
- [x] PUT code/request has been added and restructured to use MVC: Models, routes, services and controllers are separated and in different files.
- [x] No new code or functionality was added, I only restructured existing code to use MVC pattern.
- [x]  I certify that I ran my checklist

Ping @code-collabo/node-mongo

2023-04-14 15:30 UTC, samuko-things commented
I have just added the patch and put restructure. do check it out

2023-04-15 20:57 UTC, Ifycode requested changes

2023-04-15 20:57 UTC, Ifycode commented on cjs/src/api/controllers/app.controller.js
> -const express = require('express');
@samuko-things 
You probably did not read the issue title and body well.
You should only be fixing the ts template (not the esm and cjs templates).

Delete this branch and close this PR. 

Create a new branch from the develop branch and start again.

Please read the issue again properly this time and let me know if you have any questions on the community channel.

2023-04-17 09:55 UTC, samuko-things commented
ok will do

2023-04-17 09:57 UTC, closed without merging